comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch: off

